/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSetoranRouteImport } from './routes/_authenticated/setoran'
import { Route as AuthenticatedKeuanganRouteImport } from './routes/_authenticated/keuangan'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSantriIndexRouteImport } from './routes/_authenticated/santri.index'
import { Route as AuthenticatedSantriNewRouteImport } from './routes/_authenticated/santri.new'
import { Route as AuthenticatedSantriIdRouteImport } from './routes/_authenticated/santri.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSetoranRoute = AuthenticatedSetoranRouteImport.update({
  id: '/setoran',
  path: '/setoran',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeuanganRoute = AuthenticatedKeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSantriIndexRoute =
  AuthenticatedSantriIndexRouteImport.update({
    id: '/santri/',
    path: '/santri/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSantriNewRoute = AuthenticatedSantriNewRouteImport.update({
  id: '/santri/new',
  path: '/santri/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSantriIdRoute = AuthenticatedSantriIdRouteImport.update({
  id: '/santri/$id',
  path: '/santri/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/keuangan': typeof AuthenticatedKeuanganRoute
  '/setoran': typeof AuthenticatedSetoranRoute
  '/santri/$id': typeof AuthenticatedSantriIdRoute
  '/santri/new': typeof AuthenticatedSantriNewRoute
  '/santri/': typeof AuthenticatedSantriIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/keuangan': typeof AuthenticatedKeuanganRoute
  '/setoran': typeof AuthenticatedSetoranRoute
  '/santri/$id': typeof AuthenticatedSantriIdRoute
  '/santri/new': typeof AuthenticatedSantriNewRoute
  '/santri': typeof AuthenticatedSantriIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/keuangan': typeof AuthenticatedKeuanganRoute
  '/_authenticated/setoran': typeof AuthenticatedSetoranRoute
  '/_authenticated/santri/$id': typeof AuthenticatedSantriIdRoute
  '/_authenticated/santri/new': typeof AuthenticatedSantriNewRoute
  '/_authenticated/santri/': typeof AuthenticatedSantriIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/keuangan'
    | '/setoran'
    | '/santri/$id'
    | '/santri/new'
    | '/santri/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/keuangan'
    | '/setoran'
    | '/santri/$id'
    | '/santri/new'
    | '/santri'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/keuangan'
    | '/_authenticated/setoran'
    | '/_authenticated/santri/$id'
    | '/_authenticated/santri/new'
    | '/_authenticated/santri/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/setoran': {
      id: '/_authenticated/setoran'
      path: '/setoran'
      fullPath: '/setoran'
      preLoaderRoute: typeof AuthenticatedSetoranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keuangan': {
      id: '/_authenticated/keuangan'
      path: '/keuangan'
      fullPath: '/keuangan'
      preLoaderRoute: typeof AuthenticatedKeuanganRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/santri/': {
      id: '/_authenticated/santri/'
      path: '/santri'
      fullPath: '/santri/'
      preLoaderRoute: typeof AuthenticatedSantriIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/santri/new': {
      id: '/_authenticated/santri/new'
      path: '/santri/new'
      fullPath: '/santri/new'
      preLoaderRoute: typeof AuthenticatedSantriNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/santri/$id': {
      id: '/_authenticated/santri/$id'
      path: '/santri/$id'
      fullPath: '/santri/$id'
      preLoaderRoute: typeof AuthenticatedSantriIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKeuanganRoute: typeof AuthenticatedKeuanganRoute
  AuthenticatedSetoranRoute: typeof AuthenticatedSetoranRoute
  AuthenticatedSantriIdRoute: typeof AuthenticatedSantriIdRoute
  AuthenticatedSantriNewRoute: typeof AuthenticatedSantriNewRoute
  AuthenticatedSantriIndexRoute: typeof AuthenticatedSantriIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKeuanganRoute: AuthenticatedKeuanganRoute,
  AuthenticatedSetoranRoute: AuthenticatedSetoranRoute,
  AuthenticatedSantriIdRoute: AuthenticatedSantriIdRoute,
  AuthenticatedSantriNewRoute: AuthenticatedSantriNewRoute,
  AuthenticatedSantriIndexRoute: AuthenticatedSantriIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
