/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparansiRouteImport } from './routes/transparansi'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSetoranRouteImport } from './routes/_authenticated/setoran'
import { Route as AuthenticatedLaporanRouteImport } from './routes/_authenticated/laporan'
import { Route as AuthenticatedKeuanganRouteImport } from './routes/_authenticated/keuangan'
import { Route as AuthenticatedKepegawaianRouteImport } from './routes/_authenticated/kepegawaian'
import { Route as AuthenticatedHalaqahRouteImport } from './routes/_authenticated/halaqah'
import { Route as AuthenticatedDonasiRouteImport } from './routes/_authenticated/donasi'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSantriIndexRouteImport } from './routes/_authenticated/santri.index'
import { Route as AuthenticatedSantriNewRouteImport } from './routes/_authenticated/santri.new'
import { Route as AuthenticatedSantriIdRouteImport } from './routes/_authenticated/santri.$id'

const TransparansiRoute = TransparansiRouteImport.update({
  id: '/transparansi',
  path: '/transparansi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetoranRoute = AuthenticatedSetoranRouteImport.update({
  id: '/setoran',
  path: '/setoran',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaporanRoute = AuthenticatedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeuanganRoute = AuthenticatedKeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKepegawaianRoute =
  AuthenticatedKepegawaianRouteImport.update({
    id: '/kepegawaian',
    path: '/kepegawaian',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHalaqahRoute = AuthenticatedHalaqahRouteImport.update({
  id: '/halaqah',
  path: '/halaqah',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDonasiRoute = AuthenticatedDonasiRouteImport.update({
  id: '/donasi',
  path: '/donasi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSantriIndexRoute =
  AuthenticatedSantriIndexRouteImport.update({
    id: '/santri/',
    path: '/santri/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSantriNewRoute = AuthenticatedSantriNewRouteImport.update({
  id: '/santri/new',
  path: '/santri/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSantriIdRoute = AuthenticatedSantriIdRouteImport.update({
  id: '/santri/$id',
  path: '/santri/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/transparansi': typeof TransparansiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/donasi': typeof AuthenticatedDonasiRoute
  '/halaqah': typeof AuthenticatedHalaqahRoute
  '/kepegawaian': typeof AuthenticatedKepegawaianRoute
  '/keuangan': typeof AuthenticatedKeuanganRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/setoran': typeof AuthenticatedSetoranRoute
  '/users': typeof AuthenticatedUsersRoute
  '/santri/$id': typeof AuthenticatedSantriIdRoute
  '/santri/new': typeof AuthenticatedSantriNewRoute
  '/santri/': typeof AuthenticatedSantriIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/transparansi': typeof TransparansiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/donasi': typeof AuthenticatedDonasiRoute
  '/halaqah': typeof AuthenticatedHalaqahRoute
  '/kepegawaian': typeof AuthenticatedKepegawaianRoute
  '/keuangan': typeof AuthenticatedKeuanganRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/setoran': typeof AuthenticatedSetoranRoute
  '/users': typeof AuthenticatedUsersRoute
  '/santri/$id': typeof AuthenticatedSantriIdRoute
  '/santri/new': typeof AuthenticatedSantriNewRoute
  '/santri': typeof AuthenticatedSantriIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/transparansi': typeof TransparansiRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/donasi': typeof AuthenticatedDonasiRoute
  '/_authenticated/halaqah': typeof AuthenticatedHalaqahRoute
  '/_authenticated/kepegawaian': typeof AuthenticatedKepegawaianRoute
  '/_authenticated/keuangan': typeof AuthenticatedKeuanganRoute
  '/_authenticated/laporan': typeof AuthenticatedLaporanRoute
  '/_authenticated/setoran': typeof AuthenticatedSetoranRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/santri/$id': typeof AuthenticatedSantriIdRoute
  '/_authenticated/santri/new': typeof AuthenticatedSantriNewRoute
  '/_authenticated/santri/': typeof AuthenticatedSantriIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/transparansi'
    | '/dashboard'
    | '/donasi'
    | '/halaqah'
    | '/kepegawaian'
    | '/keuangan'
    | '/laporan'
    | '/setoran'
    | '/users'
    | '/santri/$id'
    | '/santri/new'
    | '/santri/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/transparansi'
    | '/dashboard'
    | '/donasi'
    | '/halaqah'
    | '/kepegawaian'
    | '/keuangan'
    | '/laporan'
    | '/setoran'
    | '/users'
    | '/santri/$id'
    | '/santri/new'
    | '/santri'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/transparansi'
    | '/_authenticated/dashboard'
    | '/_authenticated/donasi'
    | '/_authenticated/halaqah'
    | '/_authenticated/kepegawaian'
    | '/_authenticated/keuangan'
    | '/_authenticated/laporan'
    | '/_authenticated/setoran'
    | '/_authenticated/users'
    | '/_authenticated/santri/$id'
    | '/_authenticated/santri/new'
    | '/_authenticated/santri/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TransparansiRoute: typeof TransparansiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparansi': {
      id: '/transparansi'
      path: '/transparansi'
      fullPath: '/transparansi'
      preLoaderRoute: typeof TransparansiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setoran': {
      id: '/_authenticated/setoran'
      path: '/setoran'
      fullPath: '/setoran'
      preLoaderRoute: typeof AuthenticatedSetoranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan': {
      id: '/_authenticated/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthenticatedLaporanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keuangan': {
      id: '/_authenticated/keuangan'
      path: '/keuangan'
      fullPath: '/keuangan'
      preLoaderRoute: typeof AuthenticatedKeuanganRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kepegawaian': {
      id: '/_authenticated/kepegawaian'
      path: '/kepegawaian'
      fullPath: '/kepegawaian'
      preLoaderRoute: typeof AuthenticatedKepegawaianRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/halaqah': {
      id: '/_authenticated/halaqah'
      path: '/halaqah'
      fullPath: '/halaqah'
      preLoaderRoute: typeof AuthenticatedHalaqahRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/donasi': {
      id: '/_authenticated/donasi'
      path: '/donasi'
      fullPath: '/donasi'
      preLoaderRoute: typeof AuthenticatedDonasiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/santri/': {
      id: '/_authenticated/santri/'
      path: '/santri'
      fullPath: '/santri/'
      preLoaderRoute: typeof AuthenticatedSantriIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/santri/new': {
      id: '/_authenticated/santri/new'
      path: '/santri/new'
      fullPath: '/santri/new'
      preLoaderRoute: typeof AuthenticatedSantriNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/santri/$id': {
      id: '/_authenticated/santri/$id'
      path: '/santri/$id'
      fullPath: '/santri/$id'
      preLoaderRoute: typeof AuthenticatedSantriIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDonasiRoute: typeof AuthenticatedDonasiRoute
  AuthenticatedHalaqahRoute: typeof AuthenticatedHalaqahRoute
  AuthenticatedKepegawaianRoute: typeof AuthenticatedKepegawaianRoute
  AuthenticatedKeuanganRoute: typeof AuthenticatedKeuanganRoute
  AuthenticatedLaporanRoute: typeof AuthenticatedLaporanRoute
  AuthenticatedSetoranRoute: typeof AuthenticatedSetoranRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedSantriIdRoute: typeof AuthenticatedSantriIdRoute
  AuthenticatedSantriNewRoute: typeof AuthenticatedSantriNewRoute
  AuthenticatedSantriIndexRoute: typeof AuthenticatedSantriIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDonasiRoute: AuthenticatedDonasiRoute,
  AuthenticatedHalaqahRoute: AuthenticatedHalaqahRoute,
  AuthenticatedKepegawaianRoute: AuthenticatedKepegawaianRoute,
  AuthenticatedKeuanganRoute: AuthenticatedKeuanganRoute,
  AuthenticatedLaporanRoute: AuthenticatedLaporanRoute,
  AuthenticatedSetoranRoute: AuthenticatedSetoranRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedSantriIdRoute: AuthenticatedSantriIdRoute,
  AuthenticatedSantriNewRoute: AuthenticatedSantriNewRoute,
  AuthenticatedSantriIndexRoute: AuthenticatedSantriIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TransparansiRoute: TransparansiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
